/**
 * Materiales de las Subidas nativas de The Burning Crusade (resto).
 * Nombres = Wowhead ES. Reusa hierbas ya registradas en Alquimia TBC.
 */

import type { MaterialEntry } from "~/lib/guide-types";
import { ALCHEMY_TBC_MATERIALS } from "~/lib/alchemy-tbc-materials";

export const TBC_SUBIDA_MATERIALS: Record<string, MaterialEntry> = {
  ...ALCHEMY_TBC_MATERIALS,
  roughStone: { name: "Piedra férrea", itemId: 2835, icon: "inv_stone_06" },
  copperBar: { name: "Barra de cobre", itemId: 2840, icon: "inv_ingot_02" },
  coarseStone: { name: "Piedra burda", itemId: 2836, icon: "inv_stone_09" },
  silverBar: { name: "Barra de plata", itemId: 2842, icon: "inv_ingot_01" },
  bronzeBar: { name: "Barra de bronce", itemId: 2841, icon: "inv_ingot_bronze" },
  heavyStone: { name: "Piedra pesada", itemId: 2838, icon: "inv_stone_12" },
  goldBar: { name: "Barra de oro", itemId: 3577, icon: "inv_ingot_03" },
  ironBar: { name: "Barra de hierro", itemId: 3575, icon: "inv_ingot_iron" },
  greenDye: { name: "Tinte verde", itemId: 2605, icon: "inv_potion_12" },
  steelBar: { name: "Barra de acero", itemId: 3859, icon: "inv_ingot_steel" },
  solidStone: { name: "Piedra sólida", itemId: 7912, icon: "inv_stone_10" },
  mageweaveCloth: { name: "Paño de tejido mágico", itemId: 4338, icon: "inv_fabric_mageweave" },
  strangeDust: { name: "Polvo extraño", itemId: 10940, icon: "inv_enchant_duststrange" },
  lesserMagicEssence: { name: "Esencia mágica inferior", itemId: 10938, icon: "inv_enchant_essencemagicsmall" },
  greaterMagicEssence: { name: "Esencia mágica superior", itemId: 10939, icon: "inv_enchant_essencemagiclarge" },
  lesserAstralEssence: { name: "Esencia astral inferior", itemId: 10998, icon: "inv_enchant_essenceastralsmall" },
  soulDust: { name: "Polvo de alma", itemId: 11083, icon: "inv_enchant_dustsoul" },
  visionDust: { name: "Polvo de visión", itemId: 11137, icon: "inv_enchant_dustvision" },
  lesserNetherEssence: { name: "Esencia abisal inferior", itemId: 11174, icon: "inv_enchant_essencenethersmall" },
  illusionDust: { name: "Polvo de ilusión", itemId: 16204, icon: "inv_enchant_dustillusion" },
  linenCloth: { name: "Paño de lino", itemId: 2589, icon: "inv_fabric_linen_01" },
  woolCloth: { name: "Paño de lana", itemId: 2592, icon: "inv_fabric_wool_01" },
  mossAgate: { name: "Ágata musgosa", itemId: 1206, icon: "inv_misc_gem_emerald_02" },
  mediumLeather: { name: "Cuero medio", itemId: 2319, icon: "inv_misc_leatherscrap_05" },
  ruinedScraps: { name: "Restos de cuero estropeado", itemId: 2934, icon: "inv_misc_pelt_wolf_ruin_04" },
  lightLeather: { name: "Cuero ligero", itemId: 2318, icon: "inv_misc_leatherscrap_03" },
  heavyHide: { name: "Pellejo pesado", itemId: 4235, icon: "inv_misc_pelt_wolf_ruin_03" },
  heavyLeather: { name: "Cuero pesado", itemId: 4234, icon: "inv_misc_leatherscrap_07" },
  thickLeather: { name: "Cuero grueso", itemId: 4304, icon: "inv_misc_leatherscrap_08" },
  ruggedLeather: { name: "Cuero basto", itemId: 8170, icon: "inv_misc_leatherscrap_02" },
  knothideLeather: { name: "Cuero de pellejo nudoso", itemId: 21887, icon: "inv_misc_leatherscrap_10" },
  felHide: { name: "Pellejo vil", itemId: 25707, icon: "inv_misc_leatherscrap_11" },
  heavyClefthoof: { name: "Cuero uñagrieta grueso", itemId: 25708, icon: "inv_misc_leatherscrap_12" },
  silkCloth: { name: "Paño de seda", itemId: 4306, icon: "inv_fabric_silk_01" },
  runecloth: { name: "Paño rúnico", itemId: 14047, icon: "inv_fabric_purplefire_01" },
  arcaneDust: { name: "Polvo Arcano", itemId: 22445, icon: "inv_enchant_dustarcane" },
  netherwebSilk: { name: "Seda de araña Tejeabismo", itemId: 21881, icon: "inv_misc_monsterspidercarapace_01" },
  coarseThread: { name: "Hilo burdo", itemId: 2320, icon: "inv_fabric_linen_03" },
  copperOre: { name: "Mena de cobre", itemId: 2770, icon: "inv_ore_copper_01" },
  tinOre: { name: "Mena de estaño", itemId: 2771, icon: "inv_ore_tin_01" },
  silverOre: { name: "Mena de plata", itemId: 2775, icon: "inv_stone_16" },
  ironOre: { name: "Mena de hierro", itemId: 2772, icon: "inv_ore_iron_01" },
  goldOre: { name: "Mena de oro", itemId: 2776, icon: "inv_ore_gold_01" },
  mithrilOre: { name: "Mena de mitril", itemId: 3858, icon: "inv_ore_mithril_02" },
  truesilverOre: { name: "Mena de veraplata", itemId: 7911, icon: "inv_ore_truesilver_01" },
  thoriumOre: { name: "Mena de torio", itemId: 10620, icon: "inv_ore_thorium_02" },
  tigerseye: { name: "Ojo de tigre", itemId: 818, icon: "inv_misc_gem_opal_03" },
  malachite: { name: "Malaquita", itemId: 774, icon: "inv_misc_gem_emerald_03" },
  shadowgem: { name: "Gema de las Sombras", itemId: 1210, icon: "inv_misc_gem_amethyst_01" },
  lesserMoonstone: { name: "Piedra lunar inferior", itemId: 1705, icon: "inv_misc_gem_crystal_01" },
  mithrilBar: { name: "Barra de mitril", itemId: 3860, icon: "inv_ingot_06" },
  truesilverBar: { name: "Barra de veraplata", itemId: 6037, icon: "inv_ingot_08" },
  aquamarine: { name: "Aguamarina", itemId: 7909, icon: "inv_misc_gem_crystal_02" },
  simpleFlour: { name: "Harina simple", itemId: 30817, icon: "inv_misc_food_wheat_01" },
  mildSpices: { name: "Especias suaves", itemId: 2678, icon: "inv_misc_food_wheat_02" },
  chunkOfBoar: { name: "Trozo de carne de jabalí", itemId: 769, icon: "inv_misc_food_14" },
  bearMeat: { name: "Carne de oso", itemId: 3173, icon: "inv_misc_food_14" },
  stringyWolf: { name: "Carne fibrosa de lobo", itemId: 2672, icon: "inv_misc_food_14" },
  rawBrilliantSmallfish: { name: "Pececito luminoso crudo", itemId: 6291, icon: "inv_misc_fish_07" },
  rawSlitherskin: { name: "Caballa de piel escurridiza cruda", itemId: 6303, icon: "inv_misc_fish_24" },
  clamMeat: { name: "Carne de almeja", itemId: 5503, icon: "inv_misc_food_51" },
  refreshingSpringWater: { name: "Agua de manantial refrescante", itemId: 159, icon: "inv_drink_07" },
  coyoteMeat: { name: "Carne de coyote", itemId: 2673, icon: "inv_misc_food_14" },
  rawLongjaw: { name: "Pargo de lodo boquilargo crudo", itemId: 6289, icon: "inv_misc_fish_32" },
  buzzardMeat: { name: "Carne de águila ratonera", itemId: 27669, icon: "inv_misc_food_16" },
  brightBaubles: { name: "Adornos brillantes", itemId: 6532, icon: "inv_misc_gem_variety_02" },
  felIronBar: { name: "Barra de hierro vil", itemId: 23445, icon: "inv_ingot_feliron" },
  adamantiteBar: { name: "Barra de adamantita", itemId: 23446, icon: "inv_ingot_10" },
  felIronOre: { name: "Mena de hierro vil", itemId: 23424, icon: "inv_ore_feliron" },
  adamantiteOre: { name: "Mena de adamantita", itemId: 23425, icon: "inv_ore_adamantium" },
  netherweave: { name: "Madeja de tejido abisal", itemId: 21840, icon: "inv_fabric_netherweave" },
  imbuedNetherweave: { name: "Madeja de tejido abisal imbuido", itemId: 21842, icon: "inv_fabric_netherweave_bolt" },
  largePrismaticShard: { name: "Fragmento centelleante grande", itemId: 22449, icon: "inv_enchant_shardprismaticlarge" },
  moteOfEarth: { name: "Mota de tierra", itemId: 22573, icon: "inv_elemental_mote_earth01" },
  khoriumBar: { name: "Barra de korio", itemId: 23449, icon: "inv_ingot_09" },
};
